services:
  panaudio-server:
    image: ghcr.io/obiwanconobi/panaudio-server:main
    environment:
      - SqliteDB=Data Source=/Data/panaudio.db
    volumes:
      - ./Data:/Data
      - /mnt/nextcloud_2/conner/files/Music:/Music
    ports:
      - "6462:80"
    build:
      context: .
      dockerfile: Dockerfile

  frontend:
    image: ghcr.io/obiwanconobi/panaudio-server:main-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - GENERATED_ARTIST_AVATARS=${GENERATED_ARTIST_AVATARS:-true}
      - ENABLE_PLAYBACK_REPORTING=${ENABLE_PLAYBACK_REPORTING:-true}
    ports:
      - "6633:80"
    depends_on:
      - panaudio-server
